name: Build & Test RPM on Rocky 9.3 (for devel)

on:
  push:
    branches:
      # - master
      - Feature/#22435_adapt_for_devel
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9.3
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show OS info
        run: cat /etc/os-release

      - name: Install build dependencies
        run: |
          curl https://raw.githubusercontent.com/redBorder/repoinit/master/sdk9.cfg > /build/sdk9.cfg
          echo \"config_opts['use_host_resolv'] = True\" >> /build/sdk9.cfg
          ln -s /build/sdk9.cfg /etc/mock/default.cfg"
          dnf install dnf-plugins-core rpm-build make gcc git epel-release mock -y

      - name: Build RPM using mock
        run: |
          git config --global --add safe.directory /build
          cd /build/
          USERNAME=usertest VERSION=0.0.0 make rpm
          echo "RPMs generados:"
          find . -name "*.rpm"

      - name: Install generated RPM
        run: |
          RPM_FILE=$(find . -name "*.rpm" | head -n 1)
          dnf install "$RPM_FILE" -y

      - name: Run tests
        run: |
          echo "Verificando existencia del repo..."
          test -f /etc/yum.repos.d/usertest.repo

          echo "Verificando contenido del repo..."
          grep -Fx "[usertest-devel]" /etc/yum.repos.d/usertest.repo
          grep -Fx "baseurl=https://packages.redborder.com/devel/usertest/rhel/9/\$basearch/" /etc/yum.repos.d/usertest.repo
          grep -Fx "enabled=1" /etc/yum.repos.d/usertest.repo

          echo "✅ Pruebas completadas"
      # - name: Upload RPM artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: built-rpm
      #     path: |
      #       **/*.rpm